#!/usr/bin/env python
import StringIO
import httplib2
import lxml.etree
import ConfigParser
from collections import defaultdict
import sys
import os

COMMANDS = []

def command(meth):
    COMMANDS.append(meth.__name__)
    return meth
    
def getconfig(fn):
    cp = ConfigParser.SafeConfigParser()
    cp.read(fn)
    d = defaultdict(lambda: None)
    d.update(cp.items('global'))
    return d
    
class Client(httplib2.Http):
    def __init__(self, key):
        super(Client, self).__init__()
        self.add_credentials(key, "x")
    
    def get(self, url):
        resp, content = self.request(url, "GET", headers={
            "content-type": "text/xml",
        })
        if (resp["status"] == "200" or resp["status"] == "304"):
            tree = lxml.etree.parse(StringIO.StringIO(content))
            return tree, resp
        else:
            return None, resp
    
    def put(self, url, data):
        resp, content = self.request(url, "PUT", body=data,
            headers={"content-type": "text/xml"})
        
class LighthouseClient(Client):
    def __init__(self, config):
        super(LighthouseClient, self).__init__(config["key"])
        self.config = config
    
    @staticmethod
    def parse_tickets(tree, show_milestone=None):
        res = []
        for t in tree.xpath("//ticket"):
            milestone = int(t.xpath("./milestone-id")[0].text or 0)
            title = t.xpath("./title")[0].text
            number = (t.xpath("./number")[0].text)
            priority = int(t.xpath("./priority")[0].text)
            if not show_milestone or milestone==show_milestone:
                res.append((milestone, priority, number, title))
        return res
   
    @command
    def list(self, *args):
        res = []
        t = self.get(
                "http://%s.lighthouseapp.com/projects/%s/tickets.xml" % (
                self.config["account"], self.config["project"]))
        if t[0]:
            for t in sorted(self.parse_tickets(t[0], 
                            show_milestone=self.config["milestone"])):
                res.append(" ".join(str(x) for x in t[1:]))
        else:
            res.append(str(t[1]))
        return "\n".join(res)
    
    @command
    def close(self, *args):
        ticket = args[0]
        ticket = lxml.etree.Element("ticket")
        status = lxml.etree.Element("status")
        status.text = "staged"
        ticket.append(status)
        tree = lxml.etree.tostring(ticket)
        
if __name__ == "__main__":
    cfg = getconfig("settings.cfg")
    lhc = LighthouseClient(config=cfg)
    cmd = sys.argv[1]
    if cmd in COMMANDS:
        print getattr(lhc, cmd)(*sys.argv[2:])
    else:
        sys.exit(1)
